theme: jekyll-theme-hacker
# https://github.com/jeffreytse/jekyll-theme-yat
# remote_theme: "jeffreytse/jekyll-theme-yat"
plugins:
  - jekyll-remote-theme
title: Creative coding with GenArt
email: info@genart.nl
author: vincentsijben
defaults:
  home:
    heading: "GenArt"
    subheading: "Creative coding enthusiast"
    banner: "https://genart.nl/randomness/randomness-background.png"
